services:
  postgres:
    image: "${POSTGRES_IMAGE:-postgres:15.3-bookworm}"
    volumes:
      - learning-platform-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-1234}"
      POSTGRES_HOST: "${POSTGRES_HOST:-localhost}"
      POSTGRES_PORT: "${POSTGRES_PORT:-5432}"
      POSTGRES_DB: "${POSTGRES_DB:-csudh_dev}"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - postgres
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend
    environment:
      - HOST=0.0.0.0
      - WATCHPACK_POLLING=true
    volumes:
      - './frontend:/app'

volumes:
  learning-platform-data: