name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker compose build

    - name: Run the Docker container
      run: docker compose up --abort-on-container-exit

    - name: Verify container exit code
      run: |
        if [ $? -ne 0 ]; then
          echo "Container exited with errors."
          exit 1
        else
          echo "Container ran successfully."
        fi
