name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: "${POSTGRES_USER:-postgres}"
          POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-1234}"
          POSTGRES_DB: "${POSTGRES_DB:-csudh_dev}"
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          until pg_isready -h postgres -U postgres; do
            printf '.'
            sleep 5
          done

      - name: Build
        run: cd backend && go build -v ./...

      - name: Test
        run: cd backend && go test -v ./...
