name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build
        run: cd backend && go build -v ./...

      - name: Test with Retry
        run: cd backend && go test -v ./...
        
      - name: test
        run: cd backend && go test -v ./...
