name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: csudh_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Set environment variables
        run: echo "CRYPTO_KEY=$(openssl rand -base64 32)" >> $GITHUB_ENV

      - name: Install dependencies
        run: cd backend && go mod tidy

      - name: Build
        run: cd backend && go build -v ./...

      - name: Test
        env:
          DB_HOST: localhost
          DB_USER: postgres
          DB_PASSWORD: 1234
          DB_NAME: csudh_test
          DB_PORT: 5432
          CRYPTO_KEY: $(openssl rand -base64 32)
        run: cd backend && go test -cover -v ./internal/handlers/
